### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by nvdmhd** [InvisibleManVPN/InvisibleMan-VPNClient#3]
Hi,My IP address is from Iran and one time,just 1:) i could successfully Connect ; so any One has a suggstion?

**Comment by InvisibleManVPN** [comment]
> Hi,My IP address is from Iran and one time,just 1:) i could successfully Connect ; so any One has a suggstion?

@nvdmhd Hi! If I understand correctly, you could connect to VPN at the first time and can't connect the next time. Try to run the VPN as administrator and send me your feedback.
