### ISSUE TITLE
problem cant play

### ISSUE THREAD

**Issue by xcoolerboy** [InvisibleManVPN/InvisibleMan-VPNClient#9]
hello my name is soren and iam iranian {that means i need vpn for every thing} i have problem with this new update i cant play fortnite cause this new locations are so bad please get nether land 4 back it was only way to play

**Comment by InvisibleManVPN** [comment]
@xsorencoolx Hi Soren!
If you could to connect to the previous version of Invisible Man, you can download it from this link:

[Invisible Man v 2.0 x64](https://github.com/InvisibleManVPN/InvisibleMan-VPNClient/releases/download/2.0/InvisibleMan-x64.exe)

[Invisible Man v 2.0 x86](https://github.com/InvisibleManVPN/InvisibleMan-VPNClient/releases/download/2.0/InvisibleMan-x86.exe)

Try it and send us your feedback.

Good luck

**Comment by xcoolerboy** [comment]
oohhhhh thank you sir
